### ISSUE TITLE
When compiling in Ubuntu14.04 there are many “does not name type” errors

### ISSUE THREAD

**Issue by zhxxhit** [mcamplan/DSKCF_CPP#1]
parallels@ubuntu:~/vot/DSKCF_CPP-master/build$ make
Scanning dependencies of target DSKCFcpp
[  3%] Building CXX object CMakeFiles/DSKCFcpp.dir/src/cf_libs/dskcf/dskcf_tracker_run.cpp.o
In file included from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/ScaleAnalyser.hpp:51:0,
                 from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/kcf/kcf_tracker.hpp:91,
                 from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/dskcf_tracker.hpp:41,
                 from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/dskcf_tracker_run.cpp:2:
/home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/ScaleChangeObserver.hpp:65:36: error: reference to ‘Size’ is ambiguous
  virtual void onScaleChange( const Size & targetSize, const Size & windowSize, const cv::Mat2d & yf, const cv::Mat1d & cosineWindow ) = 0;
                                    ^
In file included from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/ScaleChangeObserver.hpp:43:0,
                 from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/ScaleAnalyser.hpp:51,
                 from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/kcf/kcf_tracker.hpp:91,
                 from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/dskcf_tracker.hpp:41,
                 from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/dskcf_tracker_run.cpp:2:
/home/parallels/vot/DSKCF_CPP-master/src/cf_libs/common/Typedefs.hpp:6:29: note: candidates are: typedef class cv::Size_<double> Size
 typedef cv::Size_< double > Size;
                             ^
In file included from /usr/local/include/opencv2/core.hpp:58:0,
                 from /usr/local/include/opencv2/highgui.hpp:46,
                 from /usr/local/include/opencv2/highgui/highgui.hpp:48,
                 from /home/parallels/vot/DSKCF_CPP-master/src/3rdparty/cv_ext/tracker_run.hpp:62,
                 from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/dskcf_tracker_run.hpp:39,
                 from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/dskcf_tracker_run.cpp:1:
/usr/local/include/opencv2/core/types.hpp:308:16: note:                 typedef cv::Size2i cv::Size
 typedef Size2i Size;
                ^
In file included from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/ScaleAnalyser.hpp:51:0,
                 from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/kcf/kcf_tracker.hpp:91,
                 from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/dskcf_tracker.hpp:41,
                 from /home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/dskcf_tracker_run.cpp:2:
/home/parallels/vot/DSKCF_CPP-master/src/cf_libs/dskcf/ScaleChangeObserver.hpp:65:36: error: ‘Size’ does not name a type
  virtual void onScaleChange( const Size & targetSize, const Size & windowSize, const cv::Mat2d & yf, const cv::Mat1d & cosineWindow ) = 0;

**Comment by jh14778** [comment]
This should now be fixed in the latest commit [(e80be58)](https://github.com/mcamplan/DSKCF_CPP/commit/e80be58ea8820b1325b443d7c8fc4c4f7e551e62)
