### ISSUE TITLE
How to use with kinect

### ISSUE THREAD

**Issue by DaxiongAI** [mcamplan/DSKCF_CPP#3]
How to use with kinect?please

**Comment by leihuan925** [comment]
How to use with kinect?please

**Comment by copperwiring** [comment]
@jh14778 @mcamplan  I was trying to run DSKCF with Kinect V2 on ubuntu 16.04. I tried passing a command line argument of -c <device-id-of-kinectv2> but it isn't working.

Says cannot open camera by that specified index. 

My Kinect v2 works as tested using libfreenect2
